package com.meditation.tally.ui.theme

import androidx.compose.ui.graphics.Color

// ----- ORANGE (Buddhist monk robe – saffron) -----
val SaffronPrimary = Color(0xFFC45C26)
val SaffronPrimaryVariant = Color(0xFFA34A1E)
val SaffronSecondary = Color(0xFFB8860B)
val SaffronTertiary = Color(0xFFD4842C)
val SaffronSurface = Color(0xFFFDF5EB)
val SaffronSurfaceVariant = Color(0xFFF5E6D3)
val SaffronBackgroundTop = Color(0xFFFFFBF5)
val SaffronOnSurface = Color(0xFF3E2723)
val SaffronOnSurfaceVariant = Color(0xFF5D4037)
val SaffronOutline = Color(0xFFBCAAA4)

val DarkSaffronPrimary = Color(0xFFE8922E)
val DarkSaffronPrimaryVariant = Color(0xFFD4842C)
val DarkSaffronSecondary = Color(0xFFCC7722)
val DarkSaffronTertiary = Color(0xFFE8A84C)
val DarkSaffronSurface = Color(0xFF2C1810)
val DarkSaffronSurfaceVariant = Color(0xFF3E2723)
val DarkSaffronBackground = Color(0xFF1C1412)
val DarkSaffronOnSurface = Color(0xFFFDF5EB)
val DarkSaffronOnSurfaceVariant = Color(0xFFD7CCC8)
val DarkSaffronOutline = Color(0xFF5D4037)

// ----- GREEN (mint) -----
val MintPrimary = Color(0xFF2A7A63)
val MintPrimaryVariant = Color(0xFF1D5C4A)
val MintSecondary = Color(0xFF5E9E8C)
val MintTertiary = Color(0xFF4CAF8C)
val MintSurface = Color(0xFFF0FAF5)
val MintSurfaceVariant = Color(0xFFDCEFE8)
val MintBackgroundTop = Color(0xFFF5FCF8)
val MintOnSurface = Color(0xFF163028)
val MintOnSurfaceVariant = Color(0xFF3D6558)
val MintOutline = Color(0xFF8ABFB0)

val DarkMintPrimary = Color(0xFF7DCFB6)
val DarkMintPrimaryVariant = Color(0xFF5BB89E)
val DarkMintSecondary = Color(0xFF6BAEAD)
val DarkMintTertiary = Color(0xFF4DB89A)
val DarkMintSurface = Color(0xFF192420)
val DarkMintSurfaceVariant = Color(0xFF1F2E29)
val DarkMintBackground = Color(0xFF111A17)
val DarkMintOnSurface = Color(0xFFDDF2EA)
val DarkMintOnSurfaceVariant = Color(0xFFA8CCBF)
val DarkMintOutline = Color(0xFF4A7A6E)

// ----- BLUE -----
val BluePrimary = Color(0xFF1565C0)
val BluePrimaryVariant = Color(0xFF0D47A1)
val BlueSecondary = Color(0xFF42A5F5)
val BlueTertiary = Color(0xFF29B6F6)
val BlueSurface = Color(0xFFE3F2FD)
val BlueSurfaceVariant = Color(0xFFBBDEFB)
val BlueBackgroundTop = Color(0xFFF5FAFF)
val BlueOnSurface = Color(0xFF0D1B2A)
val BlueOnSurfaceVariant = Color(0xFF1E3A5F)
val BlueOutline = Color(0xFF90CAF9)

val DarkBluePrimary = Color(0xFF64B5F6)
val DarkBluePrimaryVariant = Color(0xFF42A5F5)
val DarkBlueSecondary = Color(0xFF90CAF9)
val DarkBlueTertiary = Color(0xFF4FC3F7)
val DarkBlueSurface = Color(0xFF0D1929)
val DarkBlueSurfaceVariant = Color(0xFF1A237E)
val DarkBlueBackground = Color(0xFF0A1120)
val DarkBlueOnSurface = Color(0xFFE3F2FD)
val DarkBlueOnSurfaceVariant = Color(0xFFB3E5FC)
val DarkBlueOutline = Color(0xFF42A5F5)

// ----- PINK -----
val PinkPrimary = Color(0xFFC2185B)
val PinkPrimaryVariant = Color(0xFF880E4F)
val PinkSecondary = Color(0xFFEC407A)
val PinkTertiary = Color(0xFFF06292)
val PinkSurface = Color(0xFFFCE4EC)
val PinkSurfaceVariant = Color(0xFFF8BBD9)
val PinkBackgroundTop = Color(0xFFFFF5F8)
val PinkOnSurface = Color(0xFF3E0D1F)
val PinkOnSurfaceVariant = Color(0xFF6D1B3D)
val PinkOutline = Color(0xFFF48FB1)

val DarkPinkPrimary = Color(0xFFF06292)
val DarkPinkPrimaryVariant = Color(0xFFEC407A)
val DarkPinkSecondary = Color(0xFFF48FB1)
val DarkPinkTertiary = Color(0xFFF8BBD9)
val DarkPinkSurface = Color(0xFF2C0D1A)
val DarkPinkSurfaceVariant = Color(0xFF4A1528)
val DarkPinkBackground = Color(0xFF1A0A12)
val DarkPinkOnSurface = Color(0xFFFCE4EC)
val DarkPinkOnSurfaceVariant = Color(0xFFF8BBD9)
val DarkPinkOutline = Color(0xFFEC407A)

// ----- GREY -----
val GreyPrimary = Color(0xFF455A64)
val GreyPrimaryVariant = Color(0xFF263238)
val GreySecondary = Color(0xFF607D8B)
val GreyTertiary = Color(0xFF78909C)
val GreySurface = Color(0xFFECEFF1)
val GreySurfaceVariant = Color(0xFFCFD8DC)
val GreyBackgroundTop = Color(0xFFF5F5F5)
val GreyOnSurface = Color(0xFF263238)
val GreyOnSurfaceVariant = Color(0xFF455A64)
val GreyOutline = Color(0xFF90A4AE)

val DarkGreyPrimary = Color(0xFF90A4AE)
val DarkGreyPrimaryVariant = Color(0xFF78909C)
val DarkGreySecondary = Color(0xFFB0BEC5)
val DarkGreyTertiary = Color(0xFFCFD8DC)
val DarkGreySurface = Color(0xFF1E272C)
val DarkGreySurfaceVariant = Color(0xFF263238)
val DarkGreyBackground = Color(0xFF12171A)
val DarkGreyOnSurface = Color(0xFFECEFF1)
val DarkGreyOnSurfaceVariant = Color(0xFFB0BEC5)
val DarkGreyOutline = Color(0xFF607D8B)
